version = 0.1

[default.deploy.parameters]
stack_name = "sp-cost-aggregation-lambda-and-scheduler"
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
disable_rollback = false
parameter_overrides = [
  "AthenaDatabase=",
  "AthenaTable=",
  "AthenaQueryResultBucket=",
  "AthenaQueryResultDir=results_only_SPs/",
  "CURBucket=",
  "CSVOutputBucket=",
  "EventBridgeName=",
  "LambdaFunctionName=",
  "SPPurchaseAccountID=",
  "RootOUId="
]